"""create_questions_table

Revision ID: b5eee4b9bf76
Revises: 'None'
Create Date: 2026-09-15 08:33:29.762786

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5eee4b9bf76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'SINGLE_ANSWER', 'NOTE', name='questiontype'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_pyq', sa.Boolean(), nullable=False),
    sa.Column('exam_name', sa.String(length=100), nullable=True),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('exam_month', sa.Integer(), nullable=True),
    sa.Column('exam_day', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_chapter'), 'questions', ['chapter'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_exam_name'), 'questions', ['exam_name'], unique=False)
    op.create_index(op.f('ix_questions_exam_year'), 'questions', ['exam_year'], unique=False)
    op.create_index(op.f('ix_questions_is_pyq'), 'questions', ['is_pyq'], unique=False)
    op.create_index('ix_questions_pyq_search', 'questions', ['is_pyq', 'exam_name', 'exam_year'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_index('ix_questions_subject_chapter_topic', 'questions', ['subject', 'chapter', 'topic'], unique=False)
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index('ix_questions_subject_chapter_topic', table_name='questions')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index('ix_questions_pyq_search', table_name='questions')
    op.drop_index(op.f('ix_questions_is_pyq'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_year'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_name'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('ix_questions_chapter'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
